[project]
name = "jetbot-yolo-train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kagglehub>=0.3.13",
    "ultralytics>=8.3.235",
]

